# SPDX-FileCopyrightText: Timothée Ravier <tim@siosm.fr>
# SPDX-License-Identifier: CC0-1.0

FROM quay.io/podman/stable

RUN dnf install -y buildah skopeo --exclude container-selinux &&\
    dnf clean all &&\
    rm -rf /var/cache /var/log/dnf* /var/log/yum.*
